### PR TITLE
Implement CAIP 122

### LINKED ISSUE #25: Compliance with CAIP-122
Walt.id gave a statement that they are using "Sign in with Tezos". After asking if they mean this OS library they gave the following reply:

> Hey @dansan566 thanks for reaching out to us! Based on https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-122.md we have implemented SIWT our selves. Some docs can be found here here https://docs.walt.id/v/idpkit/concepts/identity-provision-via-nfts-with-tezos/sign-in-with-tezos-siwt

What we see here is a mix-up due to the fact that the CAIP-122 is defining the message data model for a sign in message calling it "Sign in with X" and also providing a definition for namespaces in which the namespace "tezos" with associated references is defined.

The CAIP = Chain Agnostic Improvement Proposal is an abstraction of the corresponding EIP-4361 for the Ethereum specific implementation instructions. What we need to do here is:

- [ ] Modify our message according to the data model of CAIP-122
- [ ] Create a TZIP with the Tezos specific implementation (e.g. using failing_noop) and where the nounce comes from etc
- [x] State in our docs that we comply with CAIP-122 moved to #52 
- [ ] Join as vDL the autonomous organization "Chain Agnostic"

### PR DESCRIPTION
**Pull request by royscheeren**
# Scope
Make SIWT compliant with CAIP-122 and message signing TZIPs

# Work done
- Modify the message with the required parameters as per CAIP-122
- Introduce ABNF definition and parser
- Update verify function adapt to the new format
- Update tests
- Resolves #25 #33

### CODE REVIEW

**Review by dansan566 — COMMENTED** [review]
Please add a min version of node (I used v14.17.1 and it did not work). I upgraded to the latest version (v20.11.1) and then it worked.

**Comment by dansan566** [comment]
without Terms and Conditions & Privacy Policy
Bildschirmfoto 2024-03-11 um 23 45 35
Bildschirmfoto 2024-03-11 um 23 45 46
with Terms and Conditions & Privacy Policy
Bildschirmfoto 2024-03-11 um 23 46 31

Temple Output:
Tezos Signed Message: SIWT wants you to sign in with your Tezos account: tz1Q86tz2HeTL6iwHVcYe7nGUN4zSU545nWf By signing this message, you agree to the resources mentioned in this message. Uri: https://siwt.xyz Version: 1 Chain ID: NetXnHfVqm9iesp Nonce: 12345678 Issued At: 2024-03-11T22:54:26.017Z Expiration Time: 2024-03-11T22:59:26.017Z Resources: - Terms and Conditions - Privacy Policy

**Comment by dansan566** [comment]
Got an error but can't reproduce... 
Bildschirmfoto 2024-03-11 um 23 51 41

**Comment by jdsika** [comment]
Tagging @bumblefudge as you are interested in the implementation of CAIP-122 :)

**Review by jdsika — APPROVED** [review]

**Pull request merged**
